main:
  project_name: weather-prediction
  experiment_name: development
  steps: all
data_check:
  kl_threshold: 0.2
data_segregation:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.3
modeling:
  # Fraction of remaining data to use for validation
  val_size: 0.2
  linearRegression:
    fit_intercept: True
    copy_X: True
    normalize: True
    positive: False
cities:
  London:
    id: 1
    latitude: 51.509865
    longitude: -0.118092
  Edinburgh:
    id: 2
    latitude: 55.953251
    longitude: -3.188267
  Manchester:
    id: 3
    latitude: 53.483959
    longitude: -2.244644
  Glasgow:
    id: 4
    latitude: 55.860916
    longitude: -4.251433
  Birmingham:
    id: 5
    latitude: 52.4814
    longitude: -1.8998
  Liverpool:
    id: 6
    latitude: 53.400002
    longitude: -2.983333
  Bristol:
    id: 7
    latitude: 51.4552
    longitude: -2.5967
  York:
    id: 8
    latitude: 53.958332
    longitude: -1.080278
  Oxford:
    id: 9
    latitude: 51.7522
    longitude: -1.2560
  Cardiff:
    id: 10
    latitude: 51.481583
    longitude: -3.179090