name: model_test
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.2
  - pip=23.3.1
#  - mlflow=1.23.0
#  - numpy=1.26.0
  - scikit-learn=1.3.2
#  - matplotlib=3.5.1
  - pip:
#      - wandb
#      - xgboost==1.7.5