channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.3.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - numpy==1.26.0
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.11.3
name: mlflow-env
