name: training_validation
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.3
  - mlflow=2.6.0
  - scikit-learn=1.2.2
  - matplotlib-base=3.8
  - numpy=1.26.0
  - wandb==0.15.12
  - xgboost=1.7.3