name: training_validation
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.2
  - pip=23.3.1
#  - mlflow=2.8.0
  - scikit-learn=1.3.2
#  - matplotlib=3.5.1
  - numpy=1.26.0
#  - pillow

  - pip:
#      - wandb
#      - xgboost==1.7.5