name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        environment-file: environment.yml
        python-version: '3.11.5'
        channels: conda-forge, defaults
        use-only-tar-bz2: false # IMPORTANT: This needs to be set for caching to work properly!
        auto-update-conda: true
        activate-environment: weather-prediction
    - name: Test with pytest
      shell: bash -l {0} # IMPORTANT: Use login shell to ensure conda is initialized properly
      run: |
        pytest tests/test_data_ingestion.py
        pytest tests/test_pre-processing.py
        pytest tests/test_data_checks.py
        pytest tests/test_data_segregation.py
        pytest tests/test_training_validation.py
        pytest tests/test_model_test.py
        pytest tests/test_batch_prediction.py

