name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.5'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml
    - name: Test with pytest
      run: |
        conda activate weather-prediction
        pytest tests/data_ingestion
        pytest tests/pre-processing
        pytest tests/data_checks
        pytest tests/data_segregation
        pytest tests/training_validation
        pytest tests/model_test
        pytest tests/batch_prediction
